Reorder slightly

diff --git a/scripts/all-in b/scripts/all-in
--- a/scripts/all-in
+++ b/scripts/all-in
@@ -34,12 +34,11 @@ MWD_IT_TESTS_DIRS="
 	CourseFiles936/sourcecode/ex51solution
 	CourseFiles936/sourcecode/ex52solution
 	CourseFiles936/sourcecode/ex71solution"
-# We undeploy what we deployed at the end, so students can have the fun of deploying it.
 
+# We undeploy what we deployed at the end, so students can have the fun of deploying it.
 # Get list of dirs to either do mvn clean or mvn wildfly:undeploy at end of run
 CLEAN_DIRS="jpademo jsfdemo"
 UNDEPLOY_DIRS="TicketManorJava/ticketmanor-ee"
-
 for dir in sourcecode/ex*solution; do
 	if grep -s wildfly-plugin ${dir}/pom.xml; then
 		# Script is run in CourseFiles936 but starts in .. (aka '/'), so prepend
@@ -53,15 +52,15 @@ done
 cd
 cd C:/
 
+# Excepting the two CD commands, "none shall fail"
+set -e
+
 # Make sure all repos are checked out on this machine
 for repo in ${GIT_DIRS}; do
 	if [ ! -d $repo ]; then
 		echo $0: MISSING $repo; exit 1;
 	fi
 done
-
-# Excepting the two CD commands, "none shall fail"
-set -e
 
 for repo in ${GIT_DIRS}
 do
